---

red_pods: "192.169.0.0/16"
advertise_address: "192.168.1.115/24"
puertos_kube: 
  - "6443/tcp"
  - "2379-2380/tcp"
  - "10250/tcp"
  - "10251/tcp"
  - "10252/tcp"
  - "10255/tcp"
  

# Protocol	Direction	Port Range	Purpose	                Used by
# TCP	      Inbound	  6443	      Kubernetes API Server	  All
# TCP	      Inbound	  2379-2380	  etcd server client API	kube-apiserver, etcd
# TCP	      Inbound	  10250	      Kubelet API	            self, Control Plane
# TCP	      Inbound	  10251	      kube-scheduler	        self
# TCP	      Inbound	  10252	      kube-controller-manager	self
# TCP	      Inbound	  10255	      Statistics	            Master nodes