---

- name: Configuración de exports nfs
  lineinfile:
    path: /etc/exports
    regexp: "^/srv/nfs( |\t){{ item.ip }}"
    line: "/srv/nfs {{ item.ip }}(rw,sync)"
    create: yes
  become: true
  with_items: "{{ ip_nodes }}"

- name: Re-export all shared directories
  command: exportfs -r -s
  become: true
  