---

- name: Configuración de exports nfs
  template:
    src: exports.j2
    dest: /etc/exports
  become: true


- name: Re-export all shared directories
  shell: "{{item}}"
  become: true
  with_items:
    - "exportfs -r"
    - "exportfs -s"
  