---

- name: Configuración de exports nfs
  lineinfile:
    path: /etc/exports
    regexp: "^/srv/nfs( |\t){{ item }}"
    line: "/srv/nfs {{ item }}(rw,sync)"
  become: true
  with_items:
    - "192.168.1.115"
    - "192.168.1.111"

- name: Re-export all shared directories
  command: /etc/exports/exportfs -r -s
  become: true
  