---

- name: firewall configuration for nfs
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: reloaded
    immediate: yes
  become: true
  with_items:
    - "nfs"
    - "rpc-bind"
    - "mountd"

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true