---

- name: apertura de puertos para kubernetes
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  become: true
  with_items: "{{ puertos_kube }}"



- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true