---


- name: Permitimos tráfico desde los workers
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address={{ item }} accept
    permanent: yes
    state: enabled
  become: true
  with_items: "{{ ip_workers }}"

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true