---

- name: Configuramos jubeadm
  command: ip a s docker0 | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[/][0-9]{2}' | cut -d' ' -f2
  become: true
  register: ip_docker

- name: prueba regex
  debug:
    msg: 'PRUEBA -> {{ ip_docker.stdout | regex_replace("^(?P<part1>[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\.(?P<part2>[0-9]{1,3})[/](?P<part3>[0-9]{2})$", "\\g<part1>.0[/]\\g<part3>") }}'