---

- name: Obtenemos ip docker
  shell: ip a s docker0 | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[/][0-9]{2}' | cut -d' ' -f2
  become: true
  register: ip_docker

- name: Permitimos el acceso de los contenedores a localhost
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address={{ ip_docker.stdout | regex_replace("^(?P<part1>[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\.(?P<part2>[0-9]{1,3})[/](?P<part3>[0-9]{2})$", "\g<part1>.0/\g<part3>") }} accept
    permanent: yes
    state: enabled
    zone: public
  become: true

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true