---

- name: Definimos red de PODS
  shell: "kubeadm init --apiserver-advertise-address {{ advertise_address }} --pod-network-cidr {{ red_pods }}"
  become: true
  register: kubeadm_pod_network

- name: debug
  debug: 
    var: kubeadm_pod_network
