---

- name: Definimos red de PODS
  shell: "kubeadm init --pod-network-cidr {{ red_pods }}"
  become: true
  register: kubeadm_pod_network

- name: almacenamos respuesta
  shell: "echo \"{{ kubeadm_pod_network.stdout }}\" > cosa.txt"
