---

- name: Creamos .kube para usuario root
  file:
    path: /root/.kube
    state: directory
  become: true

- name: Copiamos fichero de configuracion de kubernetes
  shell: "{{ item }}"
  become: true
  with_items:
    - unalias cp
    - cp -r /etc/kubernetes/admin.conf /root/.kube/config

- name: cambiamos propietario al fichero de configuracion
  shell: chown $(id -u):$(id -g) /root/.kube/config
  become: true

- name: Comprobamos nodos
  shell: kubectl get nodes
  become: true