---

- name: apertura de puertos para los workers
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
  become: true
  with_items: "{{ ports }}"



- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true